<a href="https://colab.research.google.com/github/vanditaagarwal/Multiple_Linear_Regression/blob/main/M20MA208_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing Libraries

import pandas as pd
import numpy as np
from sklearn import datasets, linear_model

In [ ]:
# Loading dataset

data=pd.read_csv('/content/imports-85.data', header=None)

#names=pd.read_csv('/content/imports-85.names',on_bad_lines='skip')
#pd.merge(data,names)

#data.columns=["symboling", "normalized-losses", "make", "fuel-type", "aspiration", "num-of-doors", "body-style", "drive-wheels", "engine-location", "wheel-base", "length", "width", "height", "curb-weight", "engine-type", "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "price"]
#data

df=pd.DataFrame(data)
df

df.columns =["symboling", "normalized-losses", "make", "fuel-type", "aspiration", "num-of-doors", "body-style", "drive-wheels", "engine-location", "wheel-base", "length", "width", "height", "curb-weight", "engine-type", "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke", "compression-ratio", "horsepower", "peak-rpm", "city-mpg", "highway-mpg", "price"]
df
print(data.shape)
df.head()

(205, 26)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
# Handling Missing Entries denoted with '?'

df['normalized-losses'].replace('?',0 ,inplace=True)
df['normalized-losses']=df['normalized-losses'].astype(int)
df['normalized-losses'].replace(0,df['normalized-losses'].mean(),inplace=True)
df

df['num-of-doors'].replace('?',np.nan,inplace=True)

df['bore'].replace('?',0 ,inplace=True)
df['bore']=df['bore'].astype(float)
df['bore'].replace(0,df['bore'].mean(),inplace=True)


df['stroke'].replace('?',0 ,inplace=True)
df['stroke']=df['stroke'].astype(float)
df['stroke'].replace(0,df['stroke'].mean(),inplace=True)


df['horsepower'].replace('?',0 ,inplace=True)
df['horsepower']=df['horsepower'].astype(int)
df['horsepower'].replace(0,df['horsepower'].mean(),inplace=True)


df['peak-rpm'].replace('?',0 ,inplace=True)
df['peak-rpm']=df['peak-rpm'].astype(int)
df['peak-rpm'].replace(0,df['peak-rpm'].mean(),inplace=True)


df['price'].replace('?',0 ,inplace=True)
df['price']=df['price'].astype(int)
df['price'].replace(0,df['price'].mean(),inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,97.6,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,97.6,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,97.6,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [ ]:
# Dropping Null Values

df_1=df.dropna()
df_1

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,97.6,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,97.6,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,97.6,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845.0
201,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045.0
202,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485.0
203,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470.0
204,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

In [ ]:
# Assigning dummy values to categorical columns

df_2=pd.get_dummies(df_1,columns=['make','fuel-type','aspiration','num-of-doors','body-style','drive-wheels',
                                'engine-location','engine-type','num-of-cylinders','fuel-system'], drop_first=True)
df_2

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,...,num-of-cylinders_three,num-of-cylinders_twelve,num-of-cylinders_two,fuel-system_2bbl,fuel-system_4bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,3,97.6,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
1,3,97.6,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
2,1,97.6,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,...,0,0,0,0,0,0,0,1,0,0
3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
201,-1,95.0,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
202,-1,95.0,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,...,0,0,0,0,0,0,0,1,0,0
203,-1,95.0,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
204,-1,95.0,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
# Initializing x and y

#x_1=df_2['normalized-losses']
#x_2=df_2['wheel-base']
#x_3=df_2['length']
#x_4=df_2['width']
#x_5=df_2['height']
#x_6=df_2['curb-weight']
#x_7=df_2['engine-size']
#x_8=df_2['bore']
#x_9=df_2['stroke']
#x_10=df_2['compression-ratio']
#x_11=df_2['horsepower']
#x_12=df_2['peak-rpm']
#x_13=df_2['city-mpg']
#x_14=df_2['highway-mpg']
# ......

#x=np.array([x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9, x_10, x_11, x_12, x_13, x_14])


x=df_2.drop(['price'],axis=1)
y=df_2['price']

# Except price column, all are independent columns

In [ ]:
# Normalizing featues data 'x'
x = (x - np.min(x))/(np.max(x)-np.min(x)).values

In [ ]:
# Train-Test Split (60:40)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.40,random_state=0)

In [ ]:
# Defining Linear Regression on Multiple Features

class LinearRegression() :

    def __init__( self, lr, itr ) :
        self.learning_rate = lr
        self.iterations = itr

    def fit( self, X, Y ) :
        samples, features = X.shape
        self.W = np.zeros(features)
        self.b = 0
        self.X = X.values
        self.Y = Y

        # optimization using gradient descent
        for i in range( self.iterations ) :
            Y_pred = np.dot(self.X, self.W) + self.b

            # calculating gradients
            dW = - (2*(self.X.T).dot(self.Y - Y_pred))/samples
            db = - 2 * np.sum( self.Y - Y_pred )/samples

            # updating weights
            self.W = self.W - self.learning_rate * dW
            self.b = self.b - self.learning_rate * db

    def predict( self, X ):
        answer = X.dot(self.W)+self.b
        return answer

In [ ]:
# Implementing Linear Regression on training data

multilinreg = LinearRegression( lr = 0.001,itr = 1000)
multilinreg.fit( x_train, y_train )

In [ ]:
# Predicting values for test data

y_pred = multilinreg.predict(x_test)
#y_pred1 = multilinreg.predict(x_train)

print(y_pred)
print(y_test)

#print( "Predicted values ", np.round( y_pred.values[:10], 2 ) )
#print( "Real values      ", y_test[:10] )

18      4794.500159
46     13402.465262
34      7010.409956
38      8691.377863
111    17852.355080
           ...
114    17279.597094
14     21269.980475
28      8857.975145
152     5459.305693
185    12491.890897
Length: 82, dtype: float64
18      5151.0
46     11048.0
34      7129.0
38      9095.0
111    15580.0
        ...
114    17075.0
14     24565.0
28      8921.0
152     6488.0
185     8195.0
Name: price, Length: 82, dtype: float64

In [ ]:
# Mean Square Error

from sklearn.metrics import mean_squared_error
Mse = mean_squared_error(y_test, y_pred,squared =False)
print("MSE", Mse)

MSE 4589.1504399633495

In [ ]:
# R square

from sklearn.metrics import r2_score
y_pred1 = multilinreg.predict(x_train)
r_squared = r2_score(y_train, y_pred1)

print(r_squared)

0.7361455574049203

In [ ]:
r_squared = r2_score(y_test, y_pred)

print(r_squared)

0.6620197144750132

In [ ]:
# OverfittingS

Since r2 score for training data is more than that of test data, so our model overfits.